config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  resources :foods do
    resources :comments
  end



  resources :users, only: [:new, :create, :index]



  get "users/profile" => "users#profile"

  post "/sessions" => "sessions#create"
  delete "/sessions" => "sessions#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :food

end

app/models/food.rb
class Food < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]



end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :foods
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 4}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate
#Set and allow access to current user based on current session
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method(:current_user)

#Determine if user is logged in.
  def logged_in
     !current_user.nil?
   end

#Lock users out of portions of the site if they are not logged in.
  def authenticate
    unless logged_in
      flash[:error] = "Please log in."
      redirect_to users_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.food_id = params[:food_id]
    @comment.user_id = current_user.id
    @comment.save
    redirect_to food_path(@comment.food)
  end

  def show
    @comment = Comment.find(params[:id])

  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to food_path(@comment.food)
  end


  private
  def comment_params
    params.require(:comment).permit(:body, :user_id, :food_id)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
skip_before_action :authenticate, only: [:users]

#   Prefix Verb   URI Pattern               Controller#Action
#     foods GET    /foods(.:format)          foods#index
  def index
    @foods = Food.all.shuffle
    @weather = HTTParty.get("http://api.wunderground.com/api/#{WEATHER}/conditions/q/10010.json")
  end
#           POST   /foods(.:format)          foods#create
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    @food.save
    redirect_to foods_path
  end
#  new_food GET    /foods/new(.:format)      foods#new
  def new
    @food = Food.new
  end
# edit_food GET    /foods/:id/edit(.:format) foods#edit

  def show
    @food = Food.find(params[:id])
    @comment = Comment.new

  end
#      food GET    /foods/:id(.:format)      foods#show

  def edit
    @food = Food.find(params[:id])
  end


  def update
    @food = Food.find(params[:id])
    if (current_user.id == @food.user_id) || (current_user.id == 2)
    @food.update(food_params)
    redirect_to food_path(@food)
    else
    redirect_to food_path
    flash.notice = "*you don't have access to edit this food*"
    end

  end
#           PATCH  /foods/:id(.:format)      foods#update
#           PUT    /foods/:id(.:format)      foods#update
def destroy
  @food = Food.find(params[:id])
  if (current_user.id == @food.user_id) || (current_user.id == 2)
    @food.destroy
    flash.notice = "Your food has been destroyed!"
    redirect_to foods_path
  else
    redirect_to food_path
    flash.notice = "*you don't have access to delete this food*"
  end
end
#           DELETE /foods/:id(.:format)      foods#destroy

  private
  def food_params
    params.require(:food).permit(:name, :price, :location, :image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authenticate


  def create
    username = params[:username]
    password = params[:password]
    user = User.find_by({username:username})
      if user && user.authenticate(password)
        session[:user_id] = user.id
        redirect_to foods_path
      else
        flash.notice = "*incorrect username or password*"
        redirect_to users_path
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :authenticate

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    redirect_to users_path
    flash.notice = "*please enter your username and password*"
    else
      flash.notice = "*please enter a valid username/password*"
      render new_user_path

    end
  end

  def profile
    if session[:user_id]
      @user = User.find(session[:user_id])
      redirect_to foods_path
    else
      redirect_to index_path
  end
end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<div class="comment">

  <h4>Posted <%=distance_of_time_in_words(comments.created_at,Time.now)%> ago by <username id="username">[ <%=User.find(comments.user_id).username.capitalize%> ]</username></h4>
  <p> <%= comments.body %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for [@food,@comment] do |f| %>
  <p>
    <%= f.label :body, "Logged in as: #{current_user.username}. Enter your comment below." %><br/><br>
    <%= f.text_area :body, id: "text_comment", :placeholder => "Yum, this food is awesome!" %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/foods/_form.html.erb
<%= form_for(@food, html: {multipart: true}) do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_area :name, class: "text_fields"%>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_area :price, class: "text_fields" %>
  </p>
  <p>
    <%= f.label :location %><br />
    <%= f.text_area :location, class: "text_areas", :placeholder => "Enter restaurant name, address and cross streets." %>
  </p>


  <p>
      <% if @food.image.exists? %>
      <%= image_tag @food.image.url %><br/>
      <% end %>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/foods/edit.html.erb
<h1>Update Your Food</h1>

<%= render partial: 'form' %>

app/views/foods/index.html.erb
<div id="weather">
   <img id="bug" src="<%=@weather["current_observation"]["icon_url"] %>" alt="" /><br>
<%=@weather["current_observation"]["temp_f"].to_i %>° F     <br>
<%= %>
</div>

<%flash.each do |message_type, message| %>
   <div class="alert"-<%= message_type %>"><h2><%= message %></h2></div>
 <% end %>
<h1>Get This Lunch, <%= current_user.username.capitalize%>!</h1>
<h5>Click on an image to find out where to get this lunch.</h5>



<ul>
  <% for img in @foods do %>
  <li>

  <a href="/foods/<%=img.id%>"><%= image_tag img.image.url %><br></a>
    <%=  "#{img.name} - #{number_to_currency(img.price)}"%>
  </li>


  <% end %>

</ul>

<ul>
  <li><%=button_to "Add a New Food", "foods/new", :class => "buttons", method: :get%></li>
  <li><%= button_to "Log Out", "/sessions", :class => "buttons", method: :delete%></li>
</ul>

app/views/foods/new.html.erb
<p><h1>Make a new food!</h1></p>


<%=render partial: "form"%>

app/views/foods/show.html.erb
<ul>
  <li><%= button_to "Back To Foods","/foods", :class => "buttons", method: :get %></li>
  <li><%= button_to "Update This Food", edit_food_path, :class => "buttons", method: :get%></li>
  <li><%= button_to "Delete This Food", food_path(@food), :class => "buttons", method: :delete %></li>
</ul>
<%flash.each do |message_type, message| %>
   <div class="alert"-<%= message_type %>"><h4><%= message %></h4></div>
 <% end %>

<h1>Get this <%=@food.name %>, !</h1>
<p>
<%= image_tag @food.image.url, :id => "food_img" %>
</p>
<p>
Cost: <%= number_to_currency(@food.price) %><br><br>
Where to find it: <%= @food.location %>
</p><br>

<h2>Comments</h2>

<%= render partial: 'comments/comments', collection: @food.comments %>
<%= render partial: 'comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get this lunch!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Get This Lunch!</h1>
<h4>The Lunch Finding Assistant for the Flatiron District</h4>
<br>
<div>
<h4>User Login</h4>
<p>
  <%flash.each do |message_type, message| %>
     <div class="alert"-<%= message_type %>"><h4><%= message %></h4></div>
   <% end %>
<%= form_tag '/sessions', method: :post do %>
<%= label_tag :username%>
<%= text_field_tag :username%><br>
<%= label_tag :password %>
<%= password_field_tag :password%><br>

<%= submit_tag "Log in"%>
<% end %>
<%= button_to "New User", new_user_path, method: :get%>


</p>
</div>

app/views/users/new.html.erb
<h3> New User</h3>

<%flash.each do |message_type, message| %>
   <div class="alert"-<%= message_type %>"><h4><%= message %></h4></div>
 <% end %>

<%=form_for @user do |f| %>
<%=f.label :username %>
<%=f.text_field :username %><br>
<%=f.label :password %>
<%=f.password_field :password %><br><br>
<%=f.submit "Create User" %>

<%end %>